name: Deploy Store to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch, e.g., master
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your project's Node.js version
          cache: 'npm' # Or 'yarn' if you use yarn

      - name: Install dependencies
        run: npm install # Or yarn install

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - name: List UI base directory for debugging
        run: ls -la libs/shared/ui/src/base/

      - name: Reset Nx Cache
        run: npx nx reset

      - run: npx nx affected -t lint test build

      - run: npx nx dep-graph --file=dist/graph.html

      - run: npx nx affected --target=build

      - run: npx nx show projects --affected --type=app

      - run: npx nx affected --target=deploy

      - run: npm run build

      - name: Generate timestamp
        run: |
          echo "timestamp=$(date +%s)" >> "$GITHUB_ENV"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ env.timestamp }}
          path: apps/store/dist

      - name: Upload Dependency Graph Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-graph-${{ env.timestamp }}
          path: dist/**/*

      - name: Build Store application
        run: npx nx build store --verbose
        env:
          NX_SKIP_NX_CLOUD: true
          VITE_STRIPE_PUBLISH_KEY: ${{ secrets.VITE_STRIPE_PUBLISH_KEY }}
          # NX_CLOUD_ACCESS_TOKEN will be automatically used if it's in GitHub secrets
          # Add any other build-time VITE_ environment variables here

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/store/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
